# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: tiebasign

on:
  schedule:
    #国际标准时间19点00分，北京时间需要+8小时，代表北京时间次日3点运行，延迟20m，6.2*
    - cron: "0 19 * * *"
  
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Start Sign
      env:
          BDUSS: ${{ secrets.BDUSS }}
          HOST: ${{ secrets.HOST }}
          FROM: ${{ secrets.FROM }}
          TO: ${{ secrets.TO }}
          AUTH: ${{ secrets.AUTH }}
        
      run: 
       python3 main.py
       
    - name: Create New File with Current Time
      run: |
        echo $(date) > new_file.txt

    - name: Push log #更新日志
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: set
