name: tiebasign

on:
  schedule:
    - cron: "0 19 * * *"
  
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Start Sign
      env:
          BDUSS: ${{ secrets.BDUSS }}
          HOST: ${{ secrets.HOST }}
          FROM: ${{ secrets.FROM }}
          TO: ${{ secrets.TO }}
          AUTH: ${{ secrets.AUTH }}
        
      run: 
       python3 main.py

    - name: Create run.log
      run: echo $(date -u) > run.log
      
    - name: Commit run.log
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add run.log
        git commit -m "Add run.log"
        git push
